#!/bin/bash

CURRDIR=`dirname $0`

uglifyjs $CURRDIR/src/prereq.js $CURRDIR/src/filterkit.js $CURRDIR/src/conditions.js $CURRDIR/src/filters.js $CURRDIR/src/collections.js $CURRDIR/src/collectionviews.js $CURRDIR/src/controls.js $CURRDIR/src/selectoutput.js $CURRDIR/src/util.js $CURRDIR/src/jquery.js -o filterkit.min.js --source-map filterkit.min.js.map

mv filterkit.min.js $CURRDIR/dist/
mv filterkit.min.js.map $CURRDIR/dist/

echo "" > $CURRDIR/dist/filterkit.css
find $CURRDIR/src/css -iname '*.css' -exec cat {} >> $CURRDIR/dist/filterkit.css \;
